language: zh_CN
modules:
  gae_proxy: {auto_start: 1, show_detail: 1}
  launcher: {allow_remote_connect: 1, control_port: 8985, last_run_version: 3.13.3,
    proxy: pac, xxnet_port: 8987}
  smart_router: {auto_start: 1}
  x_tunnel: {auto_start: 1}
no_mess_system: 1
